# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9445a8950371c40f317b3a802661ff4461e2faff7c5ec2210191d09348d70b4bd1cf32f0ee71c8ed0321643b13c6ae790d7f21d525f0184f5df61749769072d3

test:
  secret_key_base: 032995f7b6e23f638b83016b7545db4018e7340ac89dee3f02c6e6ea1c900552bcbb258e635a2f5c16b769975cb722a42a4c1c302f4a59bed11ac651589341c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
